# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{thumbnailer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yalcin ACIKYILDIZ"]
  s.date = %q{2010-06-12}
  s.description = %q{thumbnailer is a Ruby library for getting thumbnail images from various sites with idiotic artificial intelligence.}
  s.email = %q{yalcin}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/constants.rb",
     "lib/thumbnailer.rb",
     "lib/thumbnailer/base.rb",
     "lib/thumbnailer/fetcher.rb",
     "lib/thumbnailer/parser.rb",
     "lib/thumbnailer/sites/dailymotion.rb",
     "lib/thumbnailer/sites/flickr.rb",
     "lib/thumbnailer/sites/twitpic.rb",
     "lib/thumbnailer/sites/video_google.rb",
     "lib/thumbnailer/sites/vimeo.rb",
     "lib/thumbnailer/sites/websnapr.rb",
     "lib/thumbnailer/sites/youtube.rb",
     "thumbnailer.gemspec"
  ]
  s.homepage = %q{http://github.com/yalcin/thumbnailer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Get thumbnails from various sites}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
    else
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
  end
end

